//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "FK__bolig__departmen__398D8EEE", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kollegie.Model.department), "bolig", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kollegie.Model.bolig), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__menu__page_type__0519C6AF", "skabelon", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kollegie.Model.skabelon), "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kollegie.Model.menu), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__menu__parent__060DEAE8", "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kollegie.Model.menu), "menu1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kollegie.Model.menu), true)]
[assembly: EdmRelationshipAttribute("Model", "FK__tekst__side_id__0EA330E9", "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kollegie.Model.menu), "tekst", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kollegie.Model.tekst), true)]

#endregion

namespace Kollegie.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<bolig> boligs
        {
            get
            {
                if ((_boligs == null))
                {
                    _boligs = base.CreateObjectSet<bolig>("boligs");
                }
                return _boligs;
            }
        }
        private ObjectSet<bolig> _boligs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<department> departments
        {
            get
            {
                if ((_departments == null))
                {
                    _departments = base.CreateObjectSet<department>("departments");
                }
                return _departments;
            }
        }
        private ObjectSet<department> _departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menu> menus
        {
            get
            {
                if ((_menus == null))
                {
                    _menus = base.CreateObjectSet<menu>("menus");
                }
                return _menus;
            }
        }
        private ObjectSet<menu> _menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<nyhed> nyheds
        {
            get
            {
                if ((_nyheds == null))
                {
                    _nyheds = base.CreateObjectSet<nyhed>("nyheds");
                }
                return _nyheds;
            }
        }
        private ObjectSet<nyhed> _nyheds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<skabelon> skabelons
        {
            get
            {
                if ((_skabelons == null))
                {
                    _skabelons = base.CreateObjectSet<skabelon>("skabelons");
                }
                return _skabelons;
            }
        }
        private ObjectSet<skabelon> _skabelons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tekst> teksts
        {
            get
            {
                if ((_teksts == null))
                {
                    _teksts = base.CreateObjectSet<tekst>("teksts");
                }
                return _teksts;
            }
        }
        private ObjectSet<tekst> _teksts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the boligs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToboligs(bolig bolig)
        {
            base.AddObject("boligs", bolig);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepartments(department department)
        {
            base.AddObject("departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenus(menu menu)
        {
            base.AddObject("menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the nyheds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonyheds(nyhed nyhed)
        {
            base.AddObject("nyheds", nyhed);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the skabelons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToskabelons(skabelon skabelon)
        {
            base.AddObject("skabelons", skabelon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teksts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteksts(tekst tekst)
        {
            base.AddObject("teksts", tekst);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="bolig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bolig : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new bolig object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static bolig Createbolig(global::System.Int32 id)
        {
            bolig bolig = new bolig();
            bolig.id = id;
            return bolig;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> department
        {
            get
            {
                return _department;
            }
            set
            {
                OndepartmentChanging(value);
                ReportPropertyChanging("department");
                _department = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("department");
                OndepartmentChanged();
            }
        }
        private Nullable<global::System.Int32> _department;
        partial void OndepartmentChanging(Nullable<global::System.Int32> value);
        partial void OndepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description_dk
        {
            get
            {
                return _description_dk;
            }
            set
            {
                Ondescription_dkChanging(value);
                ReportPropertyChanging("description_dk");
                _description_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description_dk");
                Ondescription_dkChanged();
            }
        }
        private global::System.String _description_dk;
        partial void Ondescription_dkChanging(global::System.String value);
        partial void Ondescription_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description_en
        {
            get
            {
                return _description_en;
            }
            set
            {
                Ondescription_enChanging(value);
                ReportPropertyChanging("description_en");
                _description_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description_en");
                Ondescription_enChanged();
            }
        }
        private global::System.String _description_en;
        partial void Ondescription_enChanging(global::System.String value);
        partial void Ondescription_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private Nullable<global::System.Int32> _area;
        partial void OnareaChanging(Nullable<global::System.Int32> value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> surfacearea
        {
            get
            {
                return _surfacearea;
            }
            set
            {
                OnsurfaceareaChanging(value);
                ReportPropertyChanging("surfacearea");
                _surfacearea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surfacearea");
                OnsurfaceareaChanged();
            }
        }
        private Nullable<global::System.Decimal> _surfacearea;
        partial void OnsurfaceareaChanging(Nullable<global::System.Decimal> value);
        partial void OnsurfaceareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> persons
        {
            get
            {
                return _persons;
            }
            set
            {
                OnpersonsChanging(value);
                ReportPropertyChanging("persons");
                _persons = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("persons");
                OnpersonsChanged();
            }
        }
        private Nullable<global::System.Int32> _persons;
        partial void OnpersonsChanging(Nullable<global::System.Int32> value);
        partial void OnpersonsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> children
        {
            get
            {
                return _children;
            }
            set
            {
                OnchildrenChanging(value);
                ReportPropertyChanging("children");
                _children = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("children");
                OnchildrenChanged();
            }
        }
        private Nullable<global::System.Int32> _children;
        partial void OnchildrenChanging(Nullable<global::System.Int32> value);
        partial void OnchildrenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cat_amount
        {
            get
            {
                return _cat_amount;
            }
            set
            {
                Oncat_amountChanging(value);
                ReportPropertyChanging("cat_amount");
                _cat_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cat_amount");
                Oncat_amountChanged();
            }
        }
        private Nullable<global::System.Int32> _cat_amount;
        partial void Oncat_amountChanging(Nullable<global::System.Int32> value);
        partial void Oncat_amountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dog_amount
        {
            get
            {
                return _dog_amount;
            }
            set
            {
                Ondog_amountChanging(value);
                ReportPropertyChanging("dog_amount");
                _dog_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dog_amount");
                Ondog_amountChanged();
            }
        }
        private Nullable<global::System.Int32> _dog_amount;
        partial void Ondog_amountChanging(Nullable<global::System.Int32> value);
        partial void Ondog_amountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> small_pets_amount
        {
            get
            {
                return _small_pets_amount;
            }
            set
            {
                Onsmall_pets_amountChanging(value);
                ReportPropertyChanging("small_pets_amount");
                _small_pets_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("small_pets_amount");
                Onsmall_pets_amountChanged();
            }
        }
        private Nullable<global::System.Int32> _small_pets_amount;
        partial void Onsmall_pets_amountChanging(Nullable<global::System.Int32> value);
        partial void Onsmall_pets_amountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bath
        {
            get
            {
                return _bath;
            }
            set
            {
                OnbathChanging(value);
                ReportPropertyChanging("bath");
                _bath = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bath");
                OnbathChanged();
            }
        }
        private Nullable<global::System.Int32> _bath;
        partial void OnbathChanging(Nullable<global::System.Int32> value);
        partial void OnbathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kitchen
        {
            get
            {
                return _kitchen;
            }
            set
            {
                OnkitchenChanging(value);
                ReportPropertyChanging("kitchen");
                _kitchen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kitchen");
                OnkitchenChanged();
            }
        }
        private Nullable<global::System.Int32> _kitchen;
        partial void OnkitchenChanging(Nullable<global::System.Int32> value);
        partial void OnkitchenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rooms
        {
            get
            {
                return _rooms;
            }
            set
            {
                OnroomsChanging(value);
                ReportPropertyChanging("rooms");
                _rooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rooms");
                OnroomsChanged();
            }
        }
        private Nullable<global::System.Int32> _rooms;
        partial void OnroomsChanging(Nullable<global::System.Int32> value);
        partial void OnroomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> monthly_price
        {
            get
            {
                return _monthly_price;
            }
            set
            {
                Onmonthly_priceChanging(value);
                ReportPropertyChanging("monthly_price");
                _monthly_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monthly_price");
                Onmonthly_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _monthly_price;
        partial void Onmonthly_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onmonthly_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ac_expenses
        {
            get
            {
                return _ac_expenses;
            }
            set
            {
                Onac_expensesChanging(value);
                ReportPropertyChanging("ac_expenses");
                _ac_expenses = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ac_expenses");
                Onac_expensesChanged();
            }
        }
        private Nullable<global::System.Decimal> _ac_expenses;
        partial void Onac_expensesChanging(Nullable<global::System.Decimal> value);
        partial void Onac_expensesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> deposit
        {
            get
            {
                return _deposit;
            }
            set
            {
                OndepositChanging(value);
                ReportPropertyChanging("deposit");
                _deposit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deposit");
                OndepositChanged();
            }
        }
        private Nullable<global::System.Decimal> _deposit;
        partial void OndepositChanging(Nullable<global::System.Decimal> value);
        partial void OndepositChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__bolig__departmen__398D8EEE", "department")]
        public department department1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("Model.FK__bolig__departmen__398D8EEE", "department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("Model.FK__bolig__departmen__398D8EEE", "department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> department1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("Model.FK__bolig__departmen__398D8EEE", "department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("Model.FK__bolig__departmen__398D8EEE", "department", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new department object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static department Createdepartment(global::System.Int32 id)
        {
            department department = new department();
            department.id = id;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description_dk
        {
            get
            {
                return _description_dk;
            }
            set
            {
                Ondescription_dkChanging(value);
                ReportPropertyChanging("description_dk");
                _description_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description_dk");
                Ondescription_dkChanged();
            }
        }
        private global::System.String _description_dk;
        partial void Ondescription_dkChanging(global::System.String value);
        partial void Ondescription_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description_en
        {
            get
            {
                return _description_en;
            }
            set
            {
                Ondescription_enChanging(value);
                ReportPropertyChanging("description_en");
                _description_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description_en");
                Ondescription_enChanged();
            }
        }
        private global::System.String _description_en;
        partial void Ondescription_enChanging(global::System.String value);
        partial void Ondescription_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pets
        {
            get
            {
                return _pets;
            }
            set
            {
                OnpetsChanging(value);
                ReportPropertyChanging("pets");
                _pets = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pets");
                OnpetsChanged();
            }
        }
        private Nullable<global::System.Int32> _pets;
        partial void OnpetsChanging(Nullable<global::System.Int32> value);
        partial void OnpetsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pet_description
        {
            get
            {
                return _pet_description;
            }
            set
            {
                Onpet_descriptionChanging(value);
                ReportPropertyChanging("pet_description");
                _pet_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pet_description");
                Onpet_descriptionChanged();
            }
        }
        private global::System.String _pet_description;
        partial void Onpet_descriptionChanging(global::System.String value);
        partial void Onpet_descriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__bolig__departmen__398D8EEE", "bolig")]
        public EntityCollection<bolig> boligs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<bolig>("Model.FK__bolig__departmen__398D8EEE", "bolig");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<bolig>("Model.FK__bolig__departmen__398D8EEE", "bolig", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menu object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static menu Createmenu(global::System.Int32 id)
        {
            menu menu = new menu();
            menu.id = id;
            return menu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_dk
        {
            get
            {
                return _text_dk;
            }
            set
            {
                Ontext_dkChanging(value);
                ReportPropertyChanging("text_dk");
                _text_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_dk");
                Ontext_dkChanged();
            }
        }
        private global::System.String _text_dk;
        partial void Ontext_dkChanging(global::System.String value);
        partial void Ontext_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_en
        {
            get
            {
                return _text_en;
            }
            set
            {
                Ontext_enChanging(value);
                ReportPropertyChanging("text_en");
                _text_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_en");
                Ontext_enChanged();
            }
        }
        private global::System.String _text_en;
        partial void Ontext_enChanging(global::System.String value);
        partial void Ontext_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> page_type
        {
            get
            {
                return _page_type;
            }
            set
            {
                Onpage_typeChanging(value);
                ReportPropertyChanging("page_type");
                _page_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("page_type");
                Onpage_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _page_type;
        partial void Onpage_typeChanging(Nullable<global::System.Int32> value);
        partial void Onpage_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> level
        {
            get
            {
                return _level;
            }
            set
            {
                OnlevelChanging(value);
                ReportPropertyChanging("level");
                _level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("level");
                OnlevelChanged();
            }
        }
        private Nullable<global::System.Int32> _level;
        partial void OnlevelChanging(Nullable<global::System.Int32> value);
        partial void OnlevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sort
        {
            get
            {
                return _sort;
            }
            set
            {
                OnsortChanging(value);
                ReportPropertyChanging("sort");
                _sort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sort");
                OnsortChanged();
            }
        }
        private Nullable<global::System.Int32> _sort;
        partial void OnsortChanging(Nullable<global::System.Int32> value);
        partial void OnsortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parent
        {
            get
            {
                return _parent;
            }
            set
            {
                OnparentChanging(value);
                ReportPropertyChanging("parent");
                _parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent");
                OnparentChanged();
            }
        }
        private Nullable<global::System.Int32> _parent;
        partial void OnparentChanging(Nullable<global::System.Int32> value);
        partial void OnparentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__menu__page_type__0519C6AF", "skabelon")]
        public skabelon skabelon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<skabelon>("Model.FK__menu__page_type__0519C6AF", "skabelon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<skabelon>("Model.FK__menu__page_type__0519C6AF", "skabelon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<skabelon> skabelonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<skabelon>("Model.FK__menu__page_type__0519C6AF", "skabelon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<skabelon>("Model.FK__menu__page_type__0519C6AF", "skabelon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__menu__parent__060DEAE8", "menu1")]
        public EntityCollection<menu> menu1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<menu>("Model.FK__menu__parent__060DEAE8", "menu1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<menu>("Model.FK__menu__parent__060DEAE8", "menu1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__menu__parent__060DEAE8", "menu")]
        public menu menu2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("Model.FK__menu__parent__060DEAE8", "menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("Model.FK__menu__parent__060DEAE8", "menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<menu> menu2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("Model.FK__menu__parent__060DEAE8", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<menu>("Model.FK__menu__parent__060DEAE8", "menu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__tekst__side_id__0EA330E9", "tekst")]
        public EntityCollection<tekst> teksts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tekst>("Model.FK__tekst__side_id__0EA330E9", "tekst");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tekst>("Model.FK__tekst__side_id__0EA330E9", "tekst", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="nyhed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class nyhed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new nyhed object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static nyhed Createnyhed(global::System.Int32 id)
        {
            nyhed nyhed = new nyhed();
            nyhed.id = id;
            return nyhed;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String headline_dk
        {
            get
            {
                return _headline_dk;
            }
            set
            {
                Onheadline_dkChanging(value);
                ReportPropertyChanging("headline_dk");
                _headline_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("headline_dk");
                Onheadline_dkChanged();
            }
        }
        private global::System.String _headline_dk;
        partial void Onheadline_dkChanging(global::System.String value);
        partial void Onheadline_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_dk
        {
            get
            {
                return _text_dk;
            }
            set
            {
                Ontext_dkChanging(value);
                ReportPropertyChanging("text_dk");
                _text_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_dk");
                Ontext_dkChanged();
            }
        }
        private global::System.String _text_dk;
        partial void Ontext_dkChanging(global::System.String value);
        partial void Ontext_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String headline_en
        {
            get
            {
                return _headline_en;
            }
            set
            {
                Onheadline_enChanging(value);
                ReportPropertyChanging("headline_en");
                _headline_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("headline_en");
                Onheadline_enChanged();
            }
        }
        private global::System.String _headline_en;
        partial void Onheadline_enChanging(global::System.String value);
        partial void Onheadline_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_en
        {
            get
            {
                return _text_en;
            }
            set
            {
                Ontext_enChanging(value);
                ReportPropertyChanging("text_en");
                _text_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_en");
                Ontext_enChanged();
            }
        }
        private global::System.String _text_en;
        partial void Ontext_enChanging(global::System.String value);
        partial void Ontext_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _created;
        partial void OncreatedChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hidden
        {
            get
            {
                return _hidden;
            }
            set
            {
                OnhiddenChanging(value);
                ReportPropertyChanging("hidden");
                _hidden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hidden");
                OnhiddenChanged();
            }
        }
        private Nullable<global::System.Boolean> _hidden;
        partial void OnhiddenChanging(Nullable<global::System.Boolean> value);
        partial void OnhiddenChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="skabelon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class skabelon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new skabelon object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="filename">Initial value of the filename property.</param>
        public static skabelon Createskabelon(global::System.Int32 id, global::System.String filename)
        {
            skabelon skabelon = new skabelon();
            skabelon.id = id;
            skabelon.filename = filename;
            return skabelon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String filename
        {
            get
            {
                return _filename;
            }
            set
            {
                OnfilenameChanging(value);
                ReportPropertyChanging("filename");
                _filename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("filename");
                OnfilenameChanged();
            }
        }
        private global::System.String _filename;
        partial void OnfilenameChanging(global::System.String value);
        partial void OnfilenameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__menu__page_type__0519C6AF", "menu")]
        public EntityCollection<menu> menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<menu>("Model.FK__menu__page_type__0519C6AF", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<menu>("Model.FK__menu__page_type__0519C6AF", "menu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="tekst")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tekst : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tekst object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tekst Createtekst(global::System.Int32 id)
        {
            tekst tekst = new tekst();
            tekst.id = id;
            return tekst;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_dk
        {
            get
            {
                return _text_dk;
            }
            set
            {
                Ontext_dkChanging(value);
                ReportPropertyChanging("text_dk");
                _text_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_dk");
                Ontext_dkChanged();
            }
        }
        private global::System.String _text_dk;
        partial void Ontext_dkChanging(global::System.String value);
        partial void Ontext_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_en
        {
            get
            {
                return _text_en;
            }
            set
            {
                Ontext_enChanging(value);
                ReportPropertyChanging("text_en");
                _text_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_en");
                Ontext_enChanged();
            }
        }
        private global::System.String _text_en;
        partial void Ontext_enChanging(global::System.String value);
        partial void Ontext_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> side_id
        {
            get
            {
                return _side_id;
            }
            set
            {
                Onside_idChanging(value);
                ReportPropertyChanging("side_id");
                _side_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("side_id");
                Onside_idChanged();
            }
        }
        private Nullable<global::System.Int32> _side_id;
        partial void Onside_idChanging(Nullable<global::System.Int32> value);
        partial void Onside_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK__tekst__side_id__0EA330E9", "menu")]
        public menu menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("Model.FK__tekst__side_id__0EA330E9", "menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("Model.FK__tekst__side_id__0EA330E9", "menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<menu> menuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("Model.FK__tekst__side_id__0EA330E9", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<menu>("Model.FK__tekst__side_id__0EA330E9", "menu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="userlevel">Initial value of the userlevel property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.Int32 userlevel)
        {
            user user = new user();
            user.id = id;
            user.username = username;
            user.password = password;
            user.userlevel = userlevel;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userlevel
        {
            get
            {
                return _userlevel;
            }
            set
            {
                OnuserlevelChanging(value);
                ReportPropertyChanging("userlevel");
                _userlevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userlevel");
                OnuserlevelChanged();
            }
        }
        private global::System.Int32 _userlevel;
        partial void OnuserlevelChanging(global::System.Int32 value);
        partial void OnuserlevelChanged();

        #endregion
    
    }

    #endregion
    
}
