//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("tempdbModel", "FK__menu__page_type__32E0915F", "skabelon", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(tempdbModel.skabelon), "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tempdbModel.menu), true)]
[assembly: EdmRelationshipAttribute("tempdbModel", "FK__menu__parent__33D4B598", "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(tempdbModel.menu), "menu1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tempdbModel.menu), true)]
[assembly: EdmRelationshipAttribute("tempdbModel", "FK__tekst__side_id__3C69FB99", "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(tempdbModel.menu), "tekst", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tempdbModel.tekst), true)]

#endregion

namespace tempdbModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class tempdbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new tempdbEntities object using the connection string found in the 'tempdbEntities' section of the application configuration file.
        /// </summary>
        public tempdbEntities() : base("name=tempdbEntities", "tempdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tempdbEntities object.
        /// </summary>
        public tempdbEntities(string connectionString) : base(connectionString, "tempdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tempdbEntities object.
        /// </summary>
        public tempdbEntities(EntityConnection connection) : base(connection, "tempdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menu> menus
        {
            get
            {
                if ((_menus == null))
                {
                    _menus = base.CreateObjectSet<menu>("menus");
                }
                return _menus;
            }
        }
        private ObjectSet<menu> _menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<skabelon> skabelons
        {
            get
            {
                if ((_skabelons == null))
                {
                    _skabelons = base.CreateObjectSet<skabelon>("skabelons");
                }
                return _skabelons;
            }
        }
        private ObjectSet<skabelon> _skabelons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tekst> teksts
        {
            get
            {
                if ((_teksts == null))
                {
                    _teksts = base.CreateObjectSet<tekst>("teksts");
                }
                return _teksts;
            }
        }
        private ObjectSet<tekst> _teksts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenus(menu menu)
        {
            base.AddObject("menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the skabelons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToskabelons(skabelon skabelon)
        {
            base.AddObject("skabelons", skabelon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teksts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteksts(tekst tekst)
        {
            base.AddObject("teksts", tekst);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tempdbModel", Name="menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menu object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static menu Createmenu(global::System.Int32 id)
        {
            menu menu = new menu();
            menu.id = id;
            return menu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_dk
        {
            get
            {
                return _text_dk;
            }
            set
            {
                Ontext_dkChanging(value);
                ReportPropertyChanging("text_dk");
                _text_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_dk");
                Ontext_dkChanged();
            }
        }
        private global::System.String _text_dk;
        partial void Ontext_dkChanging(global::System.String value);
        partial void Ontext_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_en
        {
            get
            {
                return _text_en;
            }
            set
            {
                Ontext_enChanging(value);
                ReportPropertyChanging("text_en");
                _text_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_en");
                Ontext_enChanged();
            }
        }
        private global::System.String _text_en;
        partial void Ontext_enChanging(global::System.String value);
        partial void Ontext_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> page_type
        {
            get
            {
                return _page_type;
            }
            set
            {
                Onpage_typeChanging(value);
                ReportPropertyChanging("page_type");
                _page_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("page_type");
                Onpage_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _page_type;
        partial void Onpage_typeChanging(Nullable<global::System.Int32> value);
        partial void Onpage_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> level
        {
            get
            {
                return _level;
            }
            set
            {
                OnlevelChanging(value);
                ReportPropertyChanging("level");
                _level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("level");
                OnlevelChanged();
            }
        }
        private Nullable<global::System.Int32> _level;
        partial void OnlevelChanging(Nullable<global::System.Int32> value);
        partial void OnlevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sort
        {
            get
            {
                return _sort;
            }
            set
            {
                OnsortChanging(value);
                ReportPropertyChanging("sort");
                _sort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sort");
                OnsortChanged();
            }
        }
        private Nullable<global::System.Int32> _sort;
        partial void OnsortChanging(Nullable<global::System.Int32> value);
        partial void OnsortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parent
        {
            get
            {
                return _parent;
            }
            set
            {
                OnparentChanging(value);
                ReportPropertyChanging("parent");
                _parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent");
                OnparentChanged();
            }
        }
        private Nullable<global::System.Int32> _parent;
        partial void OnparentChanging(Nullable<global::System.Int32> value);
        partial void OnparentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tempdbModel", "FK__menu__page_type__32E0915F", "skabelon")]
        public skabelon skabelon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<skabelon>("tempdbModel.FK__menu__page_type__32E0915F", "skabelon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<skabelon>("tempdbModel.FK__menu__page_type__32E0915F", "skabelon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<skabelon> skabelonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<skabelon>("tempdbModel.FK__menu__page_type__32E0915F", "skabelon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<skabelon>("tempdbModel.FK__menu__page_type__32E0915F", "skabelon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tempdbModel", "FK__menu__parent__33D4B598", "menu1")]
        public EntityCollection<menu> menu1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<menu>("tempdbModel.FK__menu__parent__33D4B598", "menu1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<menu>("tempdbModel.FK__menu__parent__33D4B598", "menu1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tempdbModel", "FK__menu__parent__33D4B598", "menu")]
        public menu menu2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("tempdbModel.FK__menu__parent__33D4B598", "menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("tempdbModel.FK__menu__parent__33D4B598", "menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<menu> menu2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("tempdbModel.FK__menu__parent__33D4B598", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<menu>("tempdbModel.FK__menu__parent__33D4B598", "menu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tempdbModel", "FK__tekst__side_id__3C69FB99", "tekst")]
        public EntityCollection<tekst> teksts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tekst>("tempdbModel.FK__tekst__side_id__3C69FB99", "tekst");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tekst>("tempdbModel.FK__tekst__side_id__3C69FB99", "tekst", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tempdbModel", Name="skabelon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class skabelon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new skabelon object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="filename">Initial value of the filename property.</param>
        public static skabelon Createskabelon(global::System.Int32 id, global::System.String filename)
        {
            skabelon skabelon = new skabelon();
            skabelon.id = id;
            skabelon.filename = filename;
            return skabelon;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String filename
        {
            get
            {
                return _filename;
            }
            set
            {
                OnfilenameChanging(value);
                ReportPropertyChanging("filename");
                _filename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("filename");
                OnfilenameChanged();
            }
        }
        private global::System.String _filename;
        partial void OnfilenameChanging(global::System.String value);
        partial void OnfilenameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tempdbModel", "FK__menu__page_type__32E0915F", "menu")]
        public EntityCollection<menu> menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<menu>("tempdbModel.FK__menu__page_type__32E0915F", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<menu>("tempdbModel.FK__menu__page_type__32E0915F", "menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tempdbModel", Name="tekst")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tekst : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tekst object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tekst Createtekst(global::System.Int32 id)
        {
            tekst tekst = new tekst();
            tekst.id = id;
            return tekst;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_dk
        {
            get
            {
                return _text_dk;
            }
            set
            {
                Ontext_dkChanging(value);
                ReportPropertyChanging("text_dk");
                _text_dk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_dk");
                Ontext_dkChanged();
            }
        }
        private global::System.String _text_dk;
        partial void Ontext_dkChanging(global::System.String value);
        partial void Ontext_dkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text_en
        {
            get
            {
                return _text_en;
            }
            set
            {
                Ontext_enChanging(value);
                ReportPropertyChanging("text_en");
                _text_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text_en");
                Ontext_enChanged();
            }
        }
        private global::System.String _text_en;
        partial void Ontext_enChanging(global::System.String value);
        partial void Ontext_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> side_id
        {
            get
            {
                return _side_id;
            }
            set
            {
                Onside_idChanging(value);
                ReportPropertyChanging("side_id");
                _side_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("side_id");
                Onside_idChanged();
            }
        }
        private Nullable<global::System.Int32> _side_id;
        partial void Onside_idChanging(Nullable<global::System.Int32> value);
        partial void Onside_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tempdbModel", "FK__tekst__side_id__3C69FB99", "menu")]
        public menu menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("tempdbModel.FK__tekst__side_id__3C69FB99", "menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("tempdbModel.FK__tekst__side_id__3C69FB99", "menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<menu> menuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("tempdbModel.FK__tekst__side_id__3C69FB99", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<menu>("tempdbModel.FK__tekst__side_id__3C69FB99", "menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tempdbModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="userlevel">Initial value of the userlevel property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.Int32 userlevel)
        {
            user user = new user();
            user.id = id;
            user.username = username;
            user.password = password;
            user.userlevel = userlevel;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userlevel
        {
            get
            {
                return _userlevel;
            }
            set
            {
                OnuserlevelChanging(value);
                ReportPropertyChanging("userlevel");
                _userlevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userlevel");
                OnuserlevelChanged();
            }
        }
        private global::System.Int32 _userlevel;
        partial void OnuserlevelChanging(global::System.Int32 value);
        partial void OnuserlevelChanged();

        #endregion

    
    }

    #endregion

    
}
